spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5433/smarthome
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.batch_size: 50
    show-sql: false
server:
  port: 8081
kafka:
  bootstrap-servers: localhost:9092
  topics:
    snapshots: telemetry.snapshots.v1
    hubs: telemetry.hubs.v1
  groups:
    snapshots: analyzer-snapshots
    hubs: analyzer-hub-events
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

grpc:
  client:
    hub-router:
      address: 'static://127.0.0.1:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext